services:
  - type: web
    name: trend-analysis-api
    env: python
    region: ohio
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_NAME
        value: trend_analysis
      - key: CRON_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    healthCheckPath: /api/v1/health