services:
  - type: web
    name: trend-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_NAME
        value: trend_analysis 